name: lsmc_post_process
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^2.12.0

dependencies:
  http_server:
  net:
    git: https://github.com/lamtx/net.git
  path: ^1.8.0

